version: '3.3'
services:

    php:
        build:
          context: .
          dockerfile: ./Dockerfile
        container_name: project
        ports:
          - 81:80
        networks:
        - eae-network
        volumes:
          - ./:/var/www/html

    db:
      image: postgres
      container_name: postgres
      restart: always
      ports:
        - 5432:5432
      networks:
        - eae-network
      volumes:
        - ./var/lib/postgresql/data
        - ./sql.sql:/docker-entrypoint-initdb.d/sql.sql
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=pg_dev

networks:
    eae-network:
        driver: bridge